### ISSUE TITLE
Exception when no default constructor matches the DTO properties

### ISSUE THREAD

**Issue by msettlemeyer** [JonPSmith/EfCore.GenericServices#18]
Hi Jon,

I'm having an exception when attempting to use a DTO to update the DB. It looks like it might have something to do with being unable to find a constructor. I would have expected that it would fall back to Automapper in this scenario. The dtos are DDD style with private parameterless ctors and private setters on the classes. It's my understanding that Automapper can still map these types of classes because it uses reflection. Any insight you have will be greatly appreciated. Thanks.

{"Sequence contains no elements"}
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at GenericServices.Internal.Decoders.DecodedDto.GetDefaultCtorOrMethod(List`1 listToScan, String errorString)
   at GenericServices.Internal.Decoders.DecodedDto.GetCtorStaticCreatorToRun(DecodeName nameInfo, DecodedEntityClass entityInfo)
   at GenericServices.Internal.MappingCode.EntityCreateHandler`1.CreateEntityAndFillFromDto(TDto dto, String methodCtorName)
   at GenericServices.PublicButHidden.CrudServices`1.CreateAndSave[T](T entityOrDto, String ctorOrStaticMethodName)
   at CRMTests.DbTests.AccountDtoTests.CanCreateAccountFromAccountDto() in C:\***\****\CRMTests\DbTests\AccountDtoTests.cs:line 59

**Comment by msettlemeyer** [comment]
My colleague figured it out, but I think you still have a bug where First is called in GetDefaultCtorOrMethod. It wasn't matching my constructor that has 2 parameters because the parameter names were not matched up (we had recently done some refactoring).

**Comment by JonPSmith** [comment]
Hi @msettlemeyer,

Glad you found that. You are correct that I have a bug, as it should have given you a list of possible matches and tell you why they didn't match. I'll add that to me bug list.

**Comment by JonPSmith** [comment]
This is fixed in release 2.0.2
