### ISSUE TITLE
NullReferenceException when adding to services with ILinkToEntity<> to an Entity in TPH

### ISSUE THREAD

**Issue by ComtelJeremy** [JonPSmith/EfCore.GenericServices#41]
I am trying to use Generic Services with an entity that has a table per hierarchy inheritance. It appears that as soon as I run RegisterGenericServices the library throws a NullReferenceException. Is there a workaround, or is there some configuration I am not doing to enable this to work? Any guidance would be appreciated. The stack trace is below:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=GenericServices
  StackTrace:
   at GenericServices.Internal.Decoders.ParametersMatch.<>c.<get_Score>b__4_0(PropertyMatch x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at GenericServices.Internal.Decoders.ParametersMatch.get_Score()
   at GenericServices.Internal.Decoders.DecodedDto.<>c.<MatchMethodsToProperties>b__25_2(MethodCtorMatch x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GenericServices.Internal.Decoders.DecodedDto.MatchMethodsToProperties(DecodedEntityClass entityInfo)
   at GenericServices.Internal.Decoders.DecodedDto..ctor(Type dtoType, DecodedEntityClass entityInfo, IGenericServicesConfig publicConfig, PerDtoConfig perDtoConfig)
   at GenericServices.Internal.Decoders.DecodedDataCache.<>c__DisplayClass4_0.<GetOrCreateDtoInfo>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at GenericServices.Internal.Decoders.DecodedDataCache.GetOrCreateDtoInfo(Type classType, DecodedEntityClass entityInfo, IGenericServicesConfig publicConfig, PerDtoConfig perDtoConfig)
   at GenericServices.Setup.Internal.RegisterOneDtoType..ctor(Type dtoType, Type[] typesInAssembly, IGenericServicesConfig configuration)
   at GenericServices.Setup.Internal.SetupDtosAndMappings.RegisterDtosInAssemblyAndBuildMaps(Assembly assemblyToScan)
   at GenericServices.Setup.Internal.SetupDtosAndMappings.ScanAllAssemblies(Assembly[] assembliesToScan, IGenericServicesConfig config)
   at GenericServices.Setup.ConfigureGenericServices.ScanAssemblesForDtos(IGenericServicesSetupPart1 setupPart1, Assembly[] assembliesToScan)
   at ...
```

**Comment by ComtelJeremy** [comment]
Doing some more digging. It could be less related to TPH and more to having a public constructor. I'll run some more tests in the morning and let you know. The stack trace has been a little challenging to follow, but I'm getting there. :-)

**Comment by ComtelJeremy** [comment]
@JonPSmith any comment? For now I have had to handle the mapping with a Select, since I was not able to get the dto mapping to work with an TPH sub-class. I tried removing the parameterless constructor I was using for some initialization, and no joy. Any guidance you could provide would be invaluable at this point.

**Comment by JonPSmith** [comment]
I'm really busy at the moment but I'll try to have a look soon. No promises.

PS. Don't be afraid to use direct EF Core commands if GenericServices can't do something. When I write code a use GenericServices al, but if the query is complex I often write it out by hand. Also, GenericServices does provide you with the DbContext (via the Context property).

**Comment by JonPSmith** [comment]
@ComtelJeremy, Please provide the TPH classes and the DbContext that causes this problem.

**Comment by ComtelJeremy** [comment]
Thanks for the comments, @JonPSmith. I have not been able to recreate in a separate solution (that I can share), but have narrowed it down... It appears the Exception only occurs when all of the properties in the dto (including some with custom readonly mappings) are marked with the [ReadOnly(true)] attribute. If I remove even just one of those ReadOnly attributes, the web app runs. In any case, it is working now. Not sure what the root cause is, but unless I can repro I'll close this issue. Thank you for your work on this library.

**Comment by JonPSmith** [comment]
OK. Maybe there is a bug if there are all read-only, but I don't think its a big issue so I will leave it for now. 

Glad the library is useful to you. All the best with your projects.

**Comment by rfcdejong** [comment]
I get nearly the same exception, so far no idea why..

   at GenericServices.Internal.Decoders.BestPropertyMatch..ctor(String name, Type type, PropertyInfo propertyInfo)
   at GenericServices.Internal.Decoders.BestPropertyMatch.FindMatch(String name, Type type, IEnumerable`1 propertiesToCheck)
   at GenericServices.Internal.Decoders.BestPropertyMatch.FindMatch(PropertyInfo propertyToMatch, IEnumerable`1 propertiesToCheck)
   at GenericServices.Internal.Decoders.DecodedDto.<>c__DisplayClass17_0.<.ctor>b__0(PropertyInfo x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()
   at System.Collections.Immutable.ImmutableList`1.CreateRange(IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableList`1.AddRange(IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableList.ToImmutableList[TSource](IEnumerable`1 source)
   at GenericServices.Internal.Decoders.DecodedDto..ctor(Type dtoType, DecodedEntityClass entityInfo, IGenericServicesConfig publicConfig, PerDtoConfig perDtoConfig)
   at GenericServices.Internal.Decoders.DecodedDataCache.<>c__DisplayClass4_0.<GetOrCreateDtoInfo>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at GenericServices.Internal.Decoders.DecodedDataCache.GetOrCreateDtoInfo(Type classType, DecodedEntityClass entityInfo, IGenericServicesConfig publicConfig, PerDtoConfig perDtoConfig)
   at GenericServices.Setup.Internal.RegisterOneDtoType..ctor(Type dtoType, Type[] typesInAssembly, IGenericServicesConfig configuration)
   at GenericServices.Setup.Internal.SetupDtosAndMappings.RegisterDtosInAssemblyAndBuildMaps(Assembly assemblyToScan)
   at GenericServices.Setup.Internal.SetupDtosAndMappings.ScanAllAssemblies(Assembly[] assembliesToScan, IGenericServicesConfig config)
   at GenericServices.Setup.ConfigureGenericServices.ScanAssemblesForDtos(IGenericServicesSetupPart1 setupPart1, Assembly[] assembliesToScan)

**Comment by rfcdejong** [comment]
Seems my Entity has no primary key (it isn't needed) and then DecodedDto.cs line has entityInfo.PrimaryKeyProperties count 1 with a null in it so FindMatch fails

**Comment by JonPSmith** [comment]
That's a different issue. GenericServices only works with an entity that has a primary key because it loads the entity via its primary key. 

You will need to use EF Core directly for your entity that hasn't got a primary key.

**Comment by rfcdejong** [comment]
I will fill a new issue, it happens using CosmosDb and then a navigation OwnsOne to embed a resource.

**Comment by JonPSmith** [comment]
I wrote a unit test for a dto where all the properties have a `[ReadOnly(true)]` attribute on them. Couldn't get an error. Not sure what it was but I have improved the handling of nulls around the place where the exception came.
