### ISSUE TITLE
Object not set to an instance of an object

### ISSUE THREAD

**Issue by marius-stanescu** [JonPSmith/EfCore.GenericServices#47]
I am using EfCore.GenericServices 3.1.0.

I started getting a `NullReferenceException` when configuring generic services, after making a change in my entity.

The exception with stack trace:
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'
   at GenericServices.Internal.Decoders.ParametersMatch.<>c.<get_Score>b__4_0(PropertyMatch x)
   at System.Linq.Enumerable.Average[TSource](IEnumerable`1 source, Func`2 selector)
   at GenericServices.Internal.Decoders.DecodedDto.<>c.<MatchMethodsToProperties>b__25_2(MethodCtorMatch x)
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GenericServices.Internal.Decoders.DecodedDto..ctor(Type dtoType, DecodedEntityClass entityInfo, IGenericServicesConfig publicConfig, PerDtoConfig perDtoConfig)
   at GenericServices.Internal.Decoders.DecodedDataCache.<>c__DisplayClass4_0.<GetOrCreateDtoInfo>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at GenericServices.Internal.Decoders.DecodedDataCache.GetOrCreateDtoInfo(Type classType, DecodedEntityClass entityInfo, IGenericServicesConfig publicConfig, PerDtoConfig perDtoConfig)
   at GenericServices.Setup.Internal.RegisterOneDtoType..ctor(Type dtoType, Type[] typesInAssembly, IGenericServicesConfig configuration)
   at GenericServices.Setup.Internal.SetupDtosAndMappings.RegisterDtosInAssemblyAndBuildMaps(Assembly assemblyToScan)
   at GenericServices.Setup.Internal.SetupDtosAndMappings.ScanAllAssemblies(Assembly[] assembliesToScan, IGenericServicesConfig config)
   at GenericServices.Setup.ConfigureGenericServices.ScanAssemblesForDtos(IGenericServicesSetupPart1 setupPart1, Assembly[] assembliesToScan)
   at GenericServices.Setup.ConfigureGenericServices.GenericServicesSimpleSetup[TContext](IServiceCollection services, IGenericServicesConfig configuration, Assembly[] assembliesToScan)
   at Api.Startup.RegisterApiDependencies(IServiceCollection services, Assembly appAssembly, Assembly apiAssembly) in C:\Projects\Apps\SpareTime\Api\Startup.cs:line 291
   at Api.Startup.RegisterDependencies(IServiceCollection services, Assembly appAssembly, Assembly apiAssembly) in C:\Projects\Apps\SpareTime\Api\Startup.cs:line 230
   at Api.Startup.ConfigureServices(IServiceCollection services) in C:\Projects\Apps\SpareTime\Api\Startup.cs:line 83
```

This is how I configure GenericServices:
 ```
services.GenericServicesSimpleSetup<AppDbContext>(new GenericServicesConfig
{
    DirectAccessValidateOnSave = true,
    DtoAccessValidateOnSave = true,
    NoErrorOnReadSingleNull = true,
}, apiAssembly, appAssembly);
```

This is my entity (the relevant parts):
 ```
public Location()
{
	Id = Guid.NewGuid();
	CreatedOn = DateTimeOffset.Now;

	_locationFacilityMappings = new HashSet<LocationFacilityMapping>();
}

public Guid Id { get; private set; }

public DateTimeOffset CreatedOn { get; private set; }

private HashSet<LocationFacilityMapping> _locationFacilityMappings;
public IReadOnlyCollection<LocationFacilityMapping> LocationFacilityMappings
	=> _locationFacilityMappings?.ToList().AsReadOnly();
```

This is what I added in my entity:
 ```
public void AddFacilities(ICollection<Facility> facilities)
{
	foreach (var facility in facilities)
	{
		_locationFacilityMappings.Add(new LocationFacilityMapping
		{
			Facility = facility,
			Location = this,
		});
	}
}
```

**Comment by JonPSmith** [comment]
Hi @marius-stanescu ,

Can you provide the DTO that you have and also the call to the GenericServices. Thanks.

**Comment by marius-stanescu** [comment]
I have around 8 DTOs that use `ILinkToEntity<Location>`.  I think it's too much to post them all here. I couldn't figure out which one is causing the issue. Only one of the DTOs has a `Facilities` property, but I commented it out and the exception is still thrown.
This is the DTO:
```
public class SpaceLocationOutModel : ILinkToEntity<Location>
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public string Slug { get; set; }

    [ReadOnly(true)]
    public int CalendarDisplayPeriodInDays { get; set; }

    [ReadOnly(true)]
    public MapAddressViewModel Address { get; set; }

    [ReadOnly(true)]
    public IList<LocationFacilitiesModel> Facilities { get; set; }
}

public class LocationFacilitiesModel : ILinkToEntity<LocationFacilityMapping>
{
    public string Name { get; set; }
    public string Description { get; set; }
}

public class LocationFacilitiesModelConfig : PerDtoConfig<LocationFacilitiesModel, LocationFacilityMapping>
{
    public override Action<IMappingExpression<LocationFacilityMapping, LocationFacilitiesModel>> AlterReadMapping
        => cfg => cfg
            .ForMember(x => x.Description, opt => opt.MapFrom(l => l.Facility.Description))
            .ForMember(x => x.Name, opt => opt.MapFrom(l => l.Facility.Name));
}
```

**Comment by marius-stanescu** [comment]
I narrowed it down to this model. If I comment-out this model then there's no exception.

```
public class LocationAddressModel : ILinkToEntity<Location>
{
    [ReadOnly(true)]
    public int CityId { get; set; }

    [ReadOnly(true)]
    public string City { get; set; }

    [ReadOnly(true)]
    public string StreetAddress { get; set; }

    [ReadOnly(true)]
    public string PostalCode { get; set; }

    [ReadOnly(true)]
    public double? Latitude { get; set; }

    [ReadOnly(true)]
    public double? Longitude { get; set; }

    [ReadOnly(true)]
    public LocationModel Location { get; set; }

    public class LocationModel : ILinkToEntity<Location>
    {
        [ReadOnly(true)]
        public Guid Id { get; set; }

        [ReadOnly(true)]
        public string Slug { get; set; }

        [ReadOnly(true)]
        public string Name { get; set; }

        [ReadOnly(true)]
        public string PrimaryImageUrl { get; set; }

        [ReadOnly(true)]
        public ICollection<LocationSpaceModel> Spaces { get; set; }
    }

    public class LocationSpaceModel : ILinkToEntity<Space>
    {
        [ReadOnly(true)]
        public Guid Id { get; set; }

        [ReadOnly(true)]
        public string Slug { get; set; }

        [ReadOnly(true)]
        public string Name { get; set; }

        [ReadOnly(true)]
        public string Description { get; set; }

        [ReadOnly(true)]
        public string PrimaryImageUrl { get; set; }
    }
}

public class LocationAddressModelConfig : PerDtoConfig<LocationAddressModel, Location>
{
    public override Action<IMappingExpression<Location, LocationAddressModel>> AlterReadMapping
    {
        get
        {
            return cfg => cfg
                .ForMember(x => x.CityId, opt => opt.MapFrom(l => l.Address.CityId))
                .ForMember(x => x.City, opt => opt.MapFrom(l => l.Address.City.Name))
                .ForMember(x => x.StreetAddress, opt => opt.MapFrom(l => l.Address.StreetAddress))
                .ForMember(x => x.PostalCode, opt => opt.MapFrom(l => l.Address.PostalCode))
                .ForMember(x => x.Latitude, opt => opt.MapFrom(l => l.Address.Latitude))
                .ForMember(x => x.Longitude, opt => opt.MapFrom(l => l.Address.Longitude))
                .ForMember(x => x.Location, opt => opt.MapFrom(l => l));
        }
    }
}
```

**Comment by JonPSmith** [comment]
OK. Your last comment shows a class called `LocationAddressModel` with inner classes that have classes with ` ILinkToEntity<T>`. That's not allowed, as GenericServices would need to create the outer class to get as the inner classes. 

The way to handle nested data to to create separate DTO/VMs - see [this doc](https://github.com/JonPSmith/EfCore.GenericServices/wiki/GenericServices-and-DTOs#nested-dtos). 

Also, make sure you have the latest version, as there is a slightly better error messages for the type of exception you are having.

**Comment by marius-stanescu** [comment]
Ok. Thanks a lot. I'll try to fix it tomorrow and I'll let you know if it worked. Sorry, these DTOs were implemented by someone else. Didn't even realize they were nested.

**Comment by marius-stanescu** [comment]
OK, so I updated EfCore.GenericServices to the latest available version (3.2.1). The exception message is the same.

It seems that the exception is not related to the nested classes, but to the fact that the model doesn't contain any of the main entity properties, but only properties of a child entity. If I add a model property with the same name or if I alter the read mapping to use one of the properties of the main entity then the exception is not thrown anymore, even if the child model class is nested.

So, to reproduce this issue you can do something like this:
```
public class MainEntity
{
    public Guid Id { get; set; }
    public string MainEntityProperty { get; set; }
    public ChildEntity { get; set; }
}

public class ChildEntity
{
    public string ChildEntityProperty { get; set; }
}

public ChildEntityModel : ILinkToEntity<MainEntityProperty> //We want to get to the child entity via the main entity Id
{
    public string ChildEntityProperty { get; set; }
    // if there aren't any properties of the main entity defined then the exception will be thrown
    //public string MainEntityProperty { get; set } // if a main entity property is defined then the exception is not thrown anymore
}
```

I know there are multiple issues with the currently implemented models, and I'm gonna rewrite them, but I hope this example makes sense Maybe it can help someone else that made the same mistake(s).

**Comment by JonPSmith** [comment]
Yes, it does sound that there is a problem if there is no properties in the DTO/VM that match the properties in the entity class the DTO/VM links to. That can only happen on a Read, so that might be a help.

I'm deep in another project at the moment so it will be some weeks before I can look at this. I suggest you use normal EF Core code to implement your read for now.

**Comment by marius-stanescu** [comment]
Thanks a lot. For now, I just did a workaround/hack. I added a property from the main entity with a `[JsonIgnore]` attribute. So GenericServices works, all needed properties are retrieved along with the main entity property which is not displayed in the view model result because of the `JsonIgnore` attribute.

**Comment by JonPSmith** [comment]
Hi @marius-stanescu,

I tried to recreate the issue you are having and my version didn't fail - see [TestIssue47](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/Tests/UnitTests/TestIssues/TestIssue47.cs). 

Can you look at this test and check I have recreated the issue.

**Comment by JonPSmith** [comment]
I had another look at this and the problem and it must must be something to do the methods/ctors in the class in the `ILinkToEntity<T>`, but I can't spot anything.

If you want me to look at this then please provide the full definition of the the class in the `ILinkToEntity<T>`.

**Comment by marius-stanescu** [comment]
Sorry for answering late. Here is the `Location` class:

```c#
public class Location
{
    public Location()
    {
        Id = Guid.NewGuid();
        CreatedOn = DateTimeOffset.Now;

        _spaces = new HashSet<Space>();
        _locationFacilityMappings = new HashSet<LocationFacilityMapping>();
    }

    public Guid Id { get; private set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Slug { get; set; }

    public DateTimeOffset CreatedOn { get; private set; }

    public int CalendarDisplayPeriodInDays { get; set; }

    public Guid CompanyId { get; set; }
    public Company Company { get; set; }

    public Guid AddressId { get; set; }
    public MapAddress Address { get; set; }

    public int LocationTypeId { get; set; }
    public LocationType LocationType { get; set; }

    public bool IsDeleted { get; set; }

    private HashSet<Space> _spaces;
    public IReadOnlyCollection<Space> Spaces => _spaces?.ToList().AsReadOnly();

    private HashSet<LocationFacilityMapping> _locationFacilityMappings;
    public IReadOnlyCollection<LocationFacilityMapping> LocationFacilityMappings
        => _locationFacilityMappings?.ToList().AsReadOnly();

    public ICollection<LocationDaySchedule> Schedule { get; set; }

    public ICollection<LocationClosedPeriod> ClosedPeriods { get; set; }

    public void AddSpace(Space space)
    {
        Check.NotNull(space, nameof(space));

        space.Location = this;
        space.LocationId = Id;

        _spaces.Add(space);
    }

    public void AddFacilities(IEnumerable<Facility> facilities)
    {
        Check.NotNullOrEmpty(facilities, nameof(facilities));

        foreach (var facility in facilities)
        {
            _locationFacilityMappings.Add(new LocationFacilityMapping
            {
                Location = this,
                Facility = facility,
            });
        }
    }
}
```

**Comment by JonPSmith** [comment]
Hi @marius-stanescu,

I still couldn't recreate your problem. In the end I have altered some code so that it won't throw an exception where you had one, but maybe it will fail somewhere else. 

When you get a change to use it (version 3.2.2) let me know if it fixed anything. No rush.

**Comment by marius-stanescu** [comment]
Hi @JonPSmith,

I updated to 3.2.2 and the exception is not thrown anymore. So, I removed my hack/workaround of adding a new property on the model with the `[JsonIgnore]` attribute.

Thank you!

**Comment by marius-stanescu** [comment]
And about the test you wrote ([TestIssue47](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/Tests/UnitTests/TestIssues/TestIssue47.cs)), it doesn't call the `GenericServicesSimpleSetup` method, which is where the exception is thrown in my application.
It also calls `ReadManyNoTracked` as opposed to `ProjectFromEntityToDto`, which is what I have in my code.

**Comment by JonPSmith** [comment]
Hi @marius-stanescu,

Glad that fixed it! On the test:
- `SetupSingleDtoAndEntities` runs the same entity/dto code that `GenericServicesSimpleSetup` does, so it would have hit your problem if I could set up the same entity/dto setup. 
- The read was there to check that I had set it up properly, but it should have thrown an exception before this if I had set up the error case.
