### ISSUE TITLE
Unable to find static ctor

### ISSUE THREAD

**Issue by tesnep** [JonPSmith/EfCore.GenericServices#6]
I have a static ctor IStatusGeneric `<T>` CreateT()  but when I debug it, it fails to find one regardless of whether I type the string ctor name (eg CreateUser or CreateUser(5)) or leave it blank. Surprisingly, entityInfo object lists out  PublicStaticCreatorMethod as that method. It also has CanBeCreatedByCtorOrStatiMethod as true and rightly lists 0 public ctors. 

`Entity User is Hybrid with 3 methods, 0 public ctors, and 1 static class factories.`

But nameInfo has Name property always set to null and that is where it throws an Exception.
This is where it fails to find.

```c#
 public MethodCtorMatch GetCtorStaticCreatorToRun(DecodeName nameInfo, DecodedEntityClass entityInfo)
    {
      if (nameInfo.NameType != DecodedNameTypes.NoNameGiven)
        return DecodedDto.FindMethodCtorByName(nameInfo, this._matchedCtorsAndStaticMethods, "ctor/static methods");
      MethodCtorMatch defaultSetterMethod = this.GetDefaultSetterMethod(this._matchedCtorsAndStaticMethods, "ctor/static method");
      if (defaultSetterMethod != null)
        return defaultSetterMethod;
      throw new InvalidOperationException(string.Format("The entity class {0} did find an ctor/static method that matches the {1}.", (object) entityInfo.EntityType.Name, (object) this.DtoType.Name) + " It only links ctor/static methods where ALL the method's parameters can be fulfilled by the DTO/VM non-read-only properties. The possible matches are \n" + string.Join<MethodCtorMatch>("\n", (IEnumerable<MethodCtorMatch>) this._allPossibleCtorsAndStaticMatches));
    }
```

I've tried by adding PerDtoConfig mapping and removing it. As a workaround I am thinking of directly calling the static ctor from my controller.

**Comment by JonPSmith** [comment]
Hi @tesnep,

I need a bit more information to give you some feedback. The typical reason is that the properties in your DTO/ViewModel don't match the parameters in your static method. Please provide:

- The entity class, especially the static factory method
- Your DTO/ViewModel
- Your call to the `CreateAndSave` method.

I'll have a look and see what it is.

**Comment by tesnep** [comment]
Ok so here is the DTO. 
```c#
public class CreateUserDto : ILinkToEntity<User>
    {   
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; } 
         public CountryDto Country { get; set; }   
        public int CountryId { get; set; }
    }
```

This is the static method.

```C#                                       
public static IStatusGeneric<User> CreateUser(string username,
                                                string password,
                                                string email,
                                                Country country,
                                                Context context = null)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context), "You must provide a context to create a new user");
            }            
            var status = new StatusGenericHandler<User>();

            if (string.IsNullOrWhiteSpace(username))
                status.AddError($"Create User failed. Username cannot be empty", nameof(Username));
            if (string.IsNullOrWhiteSpace(password))
                status.AddError($"Create User failed. Password cannot be empty", nameof(Password));
            if (string.IsNullOrWhiteSpace(email))
                status.AddError($"Create User failed. Email cannot be empty", nameof(Email));

            if (!status.IsValid)
            {
                return status;
            }

            if (context.User.Any(x => x.Username.ToLower() == username.ToLower()))
            {
                status.AddError($"Create User failed. Username {username} already exists in database");
                return status;
            }

            var user = new User()
            {
                Username = username,
                Password = password,
                Email = email,
                CreatedDate = DateTime.Now,
                _socialMediae = new HashSet<UserSocialMedia>(),
                Country = country
            };
            
            user.Country.AddUser(user);

            status.Message = $"Created new user {username}";

            return status.SetResult(user);
        }
```

The call to CreateAndSave in controller is below.
```c#
var country =
                    await _crudServices.ReadSingleAsync<CountryDto>(x => x.Abbreviation == model.Country.Abbreviation);

                model.Country = country;
                
                var user = await _crudServices.CreateAndSaveAsync(model, "CreateUser");
//also tried
          var user = await _crudServices.CreateAndSaveAsync(model);
```

This is the exception stacktrace when I pass CreateUser string
```c#
GenericServices.IStatusGeneric`1[NtdLoop.DataLayer.Models.User] CreateUser(System.String, System.String, System.String, NtdLoop.DataLayer.Models.Country, NtdLoop.DataLayer.ModelsContext)


System.InvalidOperationException: Could not find a ctor/static methods of name CreateUser. The ctor/static methods that fit the properties in the DTO/VM are:

   at GenericServices.Internal.Decoders.DecodedDto.FindMethodCtorByName(DecodeName nameInfo, List`1 listToScan, String errorString)
   at GenericServices.Internal.Decoders.DecodedDto.GetCtorStaticCreatorToRun(DecodeName nameInfo, DecodedEntityClass entityInfo)
   at GenericServices.Internal.MappingCode.EntityCreateHandler`1.CreateEntityAndFillFromDto(TDto dto, String methodCtorName)
   at GenericServices.PublicButHidden.CrudServicesAsync`1.CreateAndSaveAsync[T](T entityOrDto, String ctorOrStaticMethodName)
   at NtdLoop.Api.Controllers.UserController.Save(CreateUserDto model) in /Users/tejaswirana/projects/RiderProjects/NtdLoop.tiny-snippets-api/NtdLoop/NtdLoop.Api/Controllers/UserController.cs:line 60
```

**Comment by tesnep** [comment]
It looks like CountryDto was the culprit. I also could not use context. But after playing around a bit, I was able to get it working.

**Comment by JonPSmith** [comment]
Hi @tesnep,

Thanks for letting me know. What was it in the end? Certainly the exception my library produced wasn't that helpful  - this there any way I can improve it?
